@startuml diagramKlasParkingAplikacja

class DateTime <<dataType>> {
  rok : UnlimitedNatural
  miesiac : UnlimitedNatural
  dzien : UnlimitedNatural
  godzina : UnlimitedNatural
  minuta : UnlimitedNatural
}

abstract class Uzytkownik {
  id : String
  login : String
  haslo : String
  imie : String
  nazwisko : String
  pesel : String
}

class Kierowca {
  numerTelefonu : String
  adresEmail : String
  stanKonta : Real
}

class Administrator {
}

class Urzednik {
}

class Zarzadca {
}

class Oplata {
  kwota : Real
  czasRozpoczecia : DateTime
  czasWaznosciBiletu : DateTime
  czyOplacone : Boolean
  numerRejestracyjny : String
  metodaPlatnosci : String
}

class Zgloszenie {
  tresc : String
  dataUtworzenia : DateTime
  dataRozpatrzenia : DateTime
  czyZatwierdzone : Boolean
}

class Parking {
  nazwa : String
  liczbaMiejsc : UnlimitedNatural
  liczbaZajetychMiejsc : UnlimitedNatural
  adres : Adres
  aktualnaCena: Real
  operator: String
  czynnyOd: DateTime
  czynnyDo: DateTime
  czyStrzezony: Boolean
}

class StatystykiParkingu {
  data : DateTime
  liczbaZajetychMiejsc : UnlimitedNatural
}

class Adres <<dataType>> {
  kraj : String
  kodPocztowy [0..1] : String
  miasto : String
  ulica [0..1] : String
  numer : String
}

Kierowca -up-|> Uzytkownik
Administrator -up-|> Uzytkownik
Urzednik -up-|> Uzytkownik
Zarzadca -up-|> Uzytkownik

Kierowca "1" -- "0..*" Oplata : płaci >
Kierowca "1" -- "0..*" Zgloszenie : zgłasza >

Administrator "1" -- "0..*" Zgloszenie : zatwierdza >

Urzednik "0..*" -- "0..*" StatystykiParkingu : analizuje >

Zarzadca "0..*" -- "0..*" Parking : zarządza >

Parking "1" o-- "0..*" StatystykiParkingu
Parking "1" -- "0..*" Oplata

@enduml
